[project]
name = "projeto-tcc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.11.1",
    "pandas>=3.0.5",
    "scikit-learn>=1.9.0",
    "torch>=2.14.0",
    "torchvision>=0.29.0",
]

[project.scripts]
projeto-tcc = "projeto_tcc:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
]
